### ISSUE TITLE
Bug in [.draws_array method(?) when using multiple cores

### ISSUE THREAD

**Issue by n-kall** [stan-dev/posterior#101] opened 2020-11-25 18:59 UTC
EDIT: Further testing shows the issue occurs with the following code and is not restricted to particular posterior version:

```
mu <- posterior::subset_draws(posterior::example_draws(), variable = "mu")
loo::relative_eff(mu, cores = 2)

Error in `[.default`(sims, , i, drop = FALSE) :
   incorrect number of dimensions
> traceback()
 12: NextMethod("[", drop = FALSE)
 11: `[.draws_array`(sims, , i)
 10: sims[, i]
 9: autocovariance(sims[, i])
 8: FUN(X[[i]], ...)
 7: lapply(1:chains, FUN = function(i) autocovariance(sims[, i]))
 6: ess_rfun(x[, , i])
 5: FUN(X[[i]], ...)
 4: lapply(X = X, FUN = FUN, ...)
 3: parallel::mclapply(mc.cores = cores, X = seq_len(dim(x)[3]),
        FUN = function(i) ess_rfun(x[, , i]))
 2: loo::relative_eff.array(mu)
 1: loo::relative_eff(mu)
```

Original report below:

It seems there is a regression in the `[.draws_array` method causing issues. The following is a reproducible example in posterior 0.1.2 (working) and posterior 0.1.3 (error)

```
# posterior_0.1.2
> mu <- posterior::subset_draws(posterior::example_draws("eight_schools"), variable = "mu")
> loo::relative_eff(mu)
      mu
1.248118
```

```
# posterior_0.1.3
> mu <- posterior::subset_draws(posterior::example_draws("eight_schools"), variable = "mu")
> loo::relative_eff(mu)
 Error in `[.default`(sims, , i, drop = FALSE) :
   incorrect number of dimensions
> traceback()
 12: NextMethod("[", drop = FALSE)
 11: `[.draws_array`(sims, , i)
 10: sims[, i]
 9: autocovariance(sims[, i])
 8: FUN(X[[i]], ...)
 7: lapply(1:chains, FUN = function(i) autocovariance(sims[, i]))
 6: ess_rfun(x[, , i])
 5: FUN(X[[i]], ...)
 4: lapply(X = X, FUN = FUN, ...)
 3: parallel::mclapply(mc.cores = cores, X = seq_len(dim(x)[3]),
        FUN = function(i) ess_rfun(x[, , i]))
 2: loo::relative_eff.array(mu)
 1: loo::relative_eff(mu)
```

**Comment by jgabry** [comment] 2020-11-25 21:09
Thanks for reporting this. I'm not actually able to reproduce it though, it seems to work fine for me. Can anyone else reproduce this?

**Comment by jgabry** [comment] 2020-11-25 21:11
Can you share the output from `sessionInfo()`?

**Comment by n-kall** [comment] 2020-11-25 22:22
Actually, it seems that I can't reproduce this in a new R session either, so it may have been due to some quirks in my current session (which still shows the behavior).
For completeness here's the `sessionInfo()` for the R session that is showing the above behavior:
```
 sessionInfo()
 R version 3.6.3 (2020-02-29)
 Platform: x86_64-pc-linux-gnu (64-bit)
 Running under: Ubuntu 18.04.5 LTS
          
 Matrix products: default
 BLAS:   /usr/lib/x86_64-linux-gnu/openblas/libblas.so.3
 LAPACK: /usr/lib/x86_64-linux-gnu/libopenblasp-r0.2.20.so
          
 locale:  
  [1] LC_CTYPE=en_GB.utf8       LC_NUMERIC=C
  [3] LC_TIME=en_DK.utf8        LC_COLLATE=en_GB.utf8
  [5] LC_MONETARY=en_GB.utf8    LC_MESSAGES=en_GB.utf8
  [7] LC_PAPER=fi_FI.utf8       LC_NAME=C
  [9] LC_ADDRESS=C              LC_TELEPHONE=C
 [11] LC_MEASUREMENT=en_GB.utf8 LC_IDENTIFICATION=C
          
 attached base packages:
 [1] stats     graphics  grDevices utils     datasets  methods   base
          
 other attached packages:
 [1] cmdstanr_0.2.1       loo_2.3.1            rstan_2.21.2
 [4] ggplot2_3.3.2        StanHeaders_2.21.0-6
          
 loaded via a namespace (and not attached):
  [1] tidyselect_1.1.0   remotes_2.2.0      purrr_0.3.4        V8_3.4.0
  [5] colorspace_2.0-0   vctrs_0.3.5        generics_0.1.0     testthat_3
  [9] usethis_1.6.3      stats4_3.6.3       rlang_0.4.8        pkgbuild_1
 [13] pillar_1.4.7       glue_1.4.2         withr_2.3.0        sessioninf
 [17] matrixStats_0.57.0 lifecycle_0.2.0    posterior_0.1.3    munsell_0.
 [21] gtable_0.3.0       devtools_2.3.2     codetools_0.2-18   memoise_1.
 [25] inline_0.3.16      callr_3.5.1        ps_1.4.0           curl_4.3
 [29] parallel_3.6.3     fansi_0.4.1        Rcpp_1.0.5         scales_1.1
 [33] backports_1.2.0    checkmate_2.0.0    desc_1.2.0         pkgload_1.
 [37] RcppParallel_5.0.2 jsonlite_1.7.1     abind_1.4-5        fs_1.5.0
 [41] gridExtra_2.3      digest_0.6.27      processx_3.4.4     dplyr_1.0.
 [45] grid_3.6.3         rprojroot_2.0.2    cli_2.2.0          tools_3.6.
 [49] magrittr_2.0.1     tibble_3.0.4       crayon_1.3.4       pkgconfig_
 [53] ellipsis_0.3.1     data.table_1.13.2  prettyunits_1.1.1  assertthat
 [57] R6_2.5.0           compiler_3.6.3
```

**Comment by jgabry** [comment] 2020-11-25 23:33
I guess that's good news that you can't reproduce it in a new session! But thanks for sharing the session info. Maybe that will help us figure out why it was happening in your other session.

**Comment by paul-buerkner** [comment] 2020-11-26 07:54
Shall we leave this issue open or close it then?

**Comment by n-kall** [comment] 2020-11-26 08:16
I'd say you can close it for now. If I run into something like this again I'll ask to reopen and hopefully have some more info on how to reproduce.

**Comment by n-kall** [comment] 2020-11-26 08:23
So, in a new R session in both versions of posterior mentioned above (0.1.2, and 0.1.3) this seems to reproduce the error (note the added options line).

```
options(mc.cores = parallel::detectCores())
mu <- posterior::subset_draws(posterior::example_draws("eight_schools"), "mu")
loo::relative_eff(mu)
```

**Comment by paul-buerkner** [comment] 2020-11-26 08:26
Oh well this code works for me on Windows.  :-D

```R
> sessionInfo()
R version 4.0.2 (2020-06-22)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18363)

Matrix products: default

locale:
[1] LC_COLLATE=German_Germany.1252  LC_CTYPE=German_Germany.1252   
[3] LC_MONETARY=German_Germany.1252 LC_NUMERIC=C                   
[5] LC_TIME=German_Germany.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.5           lubridate_1.7.9      lattice_0.20-41      prettyunits_1.1.1   
 [5] class_7.3-17         ps_1.4.0             assertthat_0.2.1     ipred_0.9-9         
 [9] foreach_1.5.0        R6_2.4.1             plyr_1.8.6           backports_1.1.10    
[13] stats4_4.0.2         ggplot2_3.3.2        pillar_1.4.6         rlang_0.4.8         
[17] caret_6.0-86         data.table_1.13.0    rstudioapi_0.11      callr_3.4.4         
[21] rpart_4.1-15         Matrix_1.2-18        checkmate_2.0.0      splines_4.0.2       
[25] stringr_1.4.0        gower_0.2.2          loo_2.3.1            munsell_0.5.0       
[29] compiler_4.0.2       rstan_2.19.3         pkgconfig_2.0.3      pkgbuild_1.1.0      
[33] nnet_7.3-14          tidyselect_1.1.0     tibble_3.0.4         gridExtra_2.3       
[37] prodlim_2019.11.13   codetools_0.2-16     matrixStats_0.57.0   fansi_0.4.1         
[41] crayon_1.3.4         dplyr_1.0.2          withr_2.2.0          ModelMetrics_1.2.2.2
[45] MASS_7.3-51.6        recipes_0.1.14       grid_4.0.2           nlme_3.1-148        
[49] gtable_0.3.0         lifecycle_0.2.0      magrittr_1.5         posterior_0.1.3     
[53] pROC_1.16.2          StanHeaders_2.21.0-6 scales_1.1.1         RcppParallel_5.0.2  
[57] stringi_1.5.3        cli_2.1.0            reshape2_1.4.4       timeDate_3043.102   
[61] ellipsis_0.3.1       generics_0.0.2       vctrs_0.3.4          lava_1.6.8          
[65] iterators_1.0.12     tools_4.0.2          glue_1.4.2           purrr_0.3.4         
[69] processx_3.4.4       abind_1.4-5          parallel_4.0.2       survival_3.1-12     
[73] inline_0.3.16        colorspace_1.4-1    
```

**Comment by n-kall** [comment] 2020-11-26 08:35
I also see this behavior on a different machine with R 4.0.3:

```
R version 4.0.3 (2020-10-10)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Debian GNU/Linux bullseye/sid

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.9.0
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.9.0

locale:
 [1] LC_CTYPE=en_AU.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_AU.UTF-8        LC_COLLATE=en_AU.UTF-8    
 [5] LC_MONETARY=en_AU.UTF-8    LC_MESSAGES=en_AU.UTF-8   
 [7] LC_PAPER=en_AU.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_AU.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.0.3     backports_1.1.10   parallel_4.0.3     abind_1.4-5       
[5] posterior_0.1.2    loo_2.3.1          checkmate_2.0.0    matrixStats_0.57.0
[9] rlang_0.4.8       
```

**Comment by rok-cesnovar** [comment] 2020-11-26 08:50
I can reproduce this on Ubuntu with the latest Github version of both posterior and loo.

**Comment by paul-buerkner** [comment] 2020-11-26 10:34
Can any of you see why this error is happening?

**Comment by rok-cesnovar** [comment] 2020-11-26 10:52
I actually think the bug is in loo. To me, it seems like setting 2 cores for 1 variable is the culprit here. The second parallel thread has nothing to do in that case and tries to access the second variable that does not exist? That is my first guess. 

Though if I try

```r
options(mc.cores = 2)
mu <- posterior::subset_draws(posterior::example_draws("eight_schools"), c("mu", "tau"))
loo::relative_eff(mu)
```
I get a different error.

**Comment by rok-cesnovar** [comment] 2020-11-26 10:53
```
options(mc.cores = 2)
mu_tau <- posterior::subset_draws(posterior::example_draws("eight_schools"), variable = c("mu", "tau"))
loo::relative_eff(mu_tau)
```
throws
```
Error in n_eff_vec/S : non-numeric argument to binary operator
In addition: Warning message:
In parallel::mclapply(mc.cores = cores, X = seq_len(dim(x)[3]),  :
```
and works fine with 1 core.

**Comment by n-kall** [comment] 2020-11-26 11:04
It seems stripping the 'draws_array' and making the object just an 'array' seems to correct the behavior. Is this an indication that the issue is in posterior?
```
mu <- posterior::subset_draws(posterior::example_draws("eight_schools"),  "mu")
class(mu) <- "array"
loo::relative_eff(mu, cores = 2)
## [1] 1.248118
```

**Comment by paul-buerkner** [comment] 2020-11-26 11:13
I have an idea: the main difference between array and draws_array is that
the latter does not drop the dimension when a single row/column/etc. Is
indexed. I would think that loo expects this automatic dropping somewhere
and then fails because the resulting object still has 3 dimensions instead
of 2.

n-kall <notifications@github.com> schrieb am Do., 26. Nov. 2020, 12:04:

**Comment by rok-cesnovar** [comment] 2020-11-26 12:21
See https://github.com/stan-dev/loo/pull/161

**Comment by jgabry** [comment] 2020-11-27 21:24
Ok with the combination of https://github.com/stan-dev/posterior/pull/102 and https://github.com/stan-dev/loo/pull/161 this should be fixed once those two PRs are both merged.

**Closed** 2020-11-30 22:29 UTC
Labels: bug
