### ISSUE TITLE
Testing the new `rvar` format in practice

### ISSUE THREAD

**Issue by paul-buerkner** [stan-dev/posterior#117] opened 2021-03-26 14:33 UTC
The recently merged `rvar` feature (#106) is a really big step forward for posterior (thank you, @mjskay)!

Due to its complexity, I expect minor problems to be popping up here and there that we should aim to iron out before the CRAN release. If you find some problems with the new format, please post them here in this issue.

**Comment by paul-buerkner** [comment] 2021-03-26 14:42
I start with a few minor discussion points:

- I see that one file is called `rvar-.R` I wonder if the `-` is intentional? Otherwise, I would rename this file.

- in `rvar()`, it seems that the `dim` argument cannot alter the first as `dim` is only used after conversion to `rvar` which suppresses the first array dimension because this is where we store draws. I agree with this behavior but this is likely to be unintuitive to R users, so it should be clearly documented.

- I think the doc pages of `rvar()` and `as_rvar()` could use some simple examples.

**Comment by bbbales2** [comment] 2021-03-31 20:37
In the vignette there seems to be a missing link:

```
do; see **TODO: INSERT LINK** for an introduction
```

Very excited about this! Thanks all

**Comment by mjskay** [comment] 2021-03-31 21:40
Thanks @paul-buerkner for opening a place to collect feedback on `rvar` stuff. I'm excited for folks to kick the tires on this!

> I see that one file is called `rvar-.R` I wonder if the `-` is intentional? Otherwise, I would rename this file.

It's a convention I've seen in other packages that keeps `rvar-.R` at the top of the directory sort order relative to other `rvar-...R` files, which I find nice when scanning through the file list. But I don't feel strongly about it, so if you don't like the convention I'll drop it. Let me know.

Re: the other two issues, adding checkboxes so I don't forget:

- [ ] betters docs for `dim` argument to `rvar()`
- [ ] simple examples for `rvar()` and `as_rvar()`

@bbbales2 thanks for reminding me, I forgot about that stub! Since that can't be filled in until the draws vignette exists, I'll add a reminder to do that in #42.

Adding one more thought: is `draws_of()` the right name for that function? The more I think about it, the function is mis-named given that it does not return a `draws` object. Perhaps `array_of()` would be better?

**Comment by paul-buerkner** [comment] 2021-04-01 06:41
Ah I remember, you have explained this `rvar-.R` to me at some point but I forgot. Thank you. 

I will have to think about the `draws_of()` idea a little more.

**Comment by avehtari** [comment] 2021-04-02 13:06
Reporting some inconsistent behavior. mean, median, quantile ok, max and min wrong result, sd error.
```
eight_schools_rvars <- as_draws_rvars(example_draws("eight_schools"))

eight_schools_rvars$mu

summarize_draws(eight_schools_rvars$mu, 'mean')
mean(eight_schools_rvars$mu)

summarize_draws(eight_schools_rvars$mu, 'median')
median(eight_schools_rvars$mu)

summarize_draws(eight_schools_rvars$mu, 'max')
max(eight_schools_rvars$mu)

summarize_draws(eight_schools_rvars$mu, 'sd')
sd(eight_schools_rvars$mu)
```

**Comment by avehtari** [comment] 2021-04-02 13:09
Also var behaves differently to sd
```
> summarize_draws(eight_schools_rvars$mu, 'var')
# A tibble: 4 x 5
  variable                  `1`    `2`    `3`    `4`
  <chr>                   <dbl>  <dbl>  <dbl>  <dbl>
1 eight_schools_rvars$mu 12.1    0.652 -0.288 -0.153
2 eight_schools_rvars$mu  0.652 17.5   -0.157 -1.46 
3 eight_schools_rvars$mu -0.288 -0.157  8.19   0.948
4 eight_schools_rvars$mu -0.153 -1.46   0.948  8.65 

> var(eight_schools_rvars$mu)
Error in var(eight_schools_rvars$mu) : is.atomic(x) is not TRUE
```

**Comment by avehtari** [comment] 2021-04-02 13:26
New sugar Pr looks nice, but then getting mcse for it there is inconsistency
```
> (eight_schools_rvars$mu>0)
rvar<100,4>[1] mean ± sd:
[1] 0.9 ± 0.31 
> Pr(eight_schools_rvars$mu>0)
[1] 0.895

> summarize_draws(eight_schools_rvars$mu>0, 'mean', mcse='mcse_mean')
# A tibble: 1 x 3
  variable                    mean   mcse
  <chr>                      <dbl>  <dbl>
1 eight_schools_rvars$mu > 0 0.895 0.0171
> summarize_draws(eight_schools_rvars$mu>0, 'Pr', mcse='mcse_mean')
Error: Can only use `Pr(...)` on logical random variables.
> summarize_draws(eight_schools_rvars$mu>0, 'E', mcse='mcse_mean')
Error in apply(draws, seq_along(dim)[-1], .f, ...) : 
  dim(X) must have a positive length
```

**Comment by avehtari** [comment] 2021-04-02 13:35
I don't know if this would make sense but adding here, that there could be something that would show the mcse in compact format. I assume it would require new variable type, like expectation variable `evar`, but I guess that could cause too much trouble even if it would look nice
```
> E(eight_schools_rvars$mu, MCSE=TRUE)
evar[1] E ± MCSE:
[1] 4.2 ± .2

> Pr(eight_schools_rvars$mu>0, MCSE=TRUE)
evar[1] Pr ± MCSE:
[1] 0.9 ± 0.02
```
Instead of an option, I guess different function name would be safer.

**Comment by mjskay** [comment] 2021-04-03 05:52
Thanks @avehtari, this is very helpful! Some notes:

## on existing summary functions

The output of min/max is the (currently) expected behavior, but I can see the inconsistency from the user side and can see why we might want to change it to be consistent with summarise_draws(). Currently, there are two kinds of summary functions for `rvar`s:

1. summary functions that are intended to mimic base-R vector summary functions, except applied to rvar vectors. These apply their summaries **across** elements of the input vectors **within** each draw. So, for example, max(X, Y) yields an rvar Z such that Z ~ max(X,Y):
  
   ```r
   x = rvar_rng(rnorm, 1, mean = 1, sd = 1)
   y = rvar_rng(rnorm, 1, mean = 2, sd = 1)
   max(x,y)
   ## rvar<4000>[1] mean ± sd:
   ## [1] 2.2 ± 0.86 
   ```

   These functions include everything in the rvar implementation of the `Summary` group generic (see `help("Summary.rvar")`): `all()`, `any()`, `sum()`, `prod()`, `min()`, `max()`, and `range()`. The `rvar_mean()` and `rvar_median()` functions also are provided to act like `mean()` and `median()` do on base-R vectors, because the `mean()` and `median()` implementations for `rvar` belong to the second group...

2. summary functions that summarise **within** elements of input vectors and **over** draws. These are the summary functions I think you are looking for (see `help("rvar-summaries")`): currently `mean()`, `median()`, `E()`, `Pr()`, `variance()`.

  To contrast `rvar_mean()` (from group 1) and `mean()` (from group 2):

```r
x = rvar_rng(rnorm, 4, mean = 1:4)
x
## rvar<4000>[4] mean ± sd:
## [1] 1 ± 0.98  2 ± 1.01  3 ± 1.00  4 ± 0.99 
rvar_mean(x)
## rvar<4000>[1] mean ± sd:
## [1] 2.5 ± 0.5 
mean(x)
## [1] 1.018346 2.005403 3.000309 3.972248
```

I think this can be better documented, but also can be made more consistent. One way to make it more consistent might be to have all the functions from the first group be prefixed by `rvar_` (mnemonically: they create new random variables) and all the functions from the second group not, then I could add a table of these functions to the `rvar` vignette. **That would lead to this proposal:**

| Summaries within draws (returns an rvar) | Summaries across draws (returns a numeric array of same shape as input rvar) |
|-----|---------|
| `rvar_mean()`, `rvar_median()`, `rvar_all()`, `rvar_any()`, `rvar_sum()`, `rvar_prod()`, `rvar_min()`, `rvar_max()`, and `rvar_range()` | `mean()`, `median()`, `all()`, `any()`, `sum()`, `prod()`, `min()`, `max()`, and `range()` |

`range()` might have to be a special case (adding an extra dimension to the input shape). This would make the API more consistent, though I wonder if some of the resulting functions are truly useful --- is there a need for `sum()` or `prod()`, or is only `rvar_sum()` / `rvar_prod()` useful? Would be curious your thoughts.

If it is desirable to have the close correspondence between summary functions in group 2 and functions that can be passed to `summarise_draws()`, we may also want to provide implementations of `rhat_...`, `ess_...` etc that just apply the basic functions across every cell of an rvar. What do you think @paul-buerkner?

## on `sd()`

The base `sd()` function unfortunately is not generic, so I did not add an `rvar` implementation of it. This is also why I am using `variance()` instead of `var()`; `variance()` is from the {generics} package and is also what {distributional} uses for getting the variance of vectors of distribution objects. However, your question prompted me to dig into it more and it seems making non-generic base functions generic in order to provide custom implementations is officially endorsed as kosher (see [here](https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Adding-new-generics)). So if folks want to do that we can. 

## on `E()` / `Pr()` with `summarise_draws()`

Ah, I didn't think of that! It should be easy enough to provide an implementation of both for numerics, which should allow them to be used with `summarise_draws()`

## on adding a separate type for means + MCSEs

I think it's a neat idea! I'd suggest spinning that off as a separate issue, as creating a new vector type can be nontrivial. Would also be good to consider the pros/cons of adding a new type versus having an easy way to get the desired two-column output. Are there operations on (mean, mcse) pairs (or vectors of such pairs) we want to implement? Possibly we could build it on top of `distributional::dist_normal()`?

## on `var()`'s strange output in `summarise_draws()`

I dug into this and it turns out this is not related to `rvar`, but happens on all types of `draws` objects. The culprit is the fact that (like so many things in R) `var()` tries to be too clever for its own good. It returns the variance if an array has dims != 2, but if it has dims == 2 (i.e. is a matrix), it returns the covariance matrix for the columns of the input (given the existence of the `cov()` function this behavior is positively dumbfounding). Since internally `summarise_draws()` converts each variable to an iterations x chains matrix prior to calling the summary function, you are getting the covariance matrix for the chains as output (hence columns `1` `2` `3` `4`). 

I defer to @paul-buerkner on how he wants to solve this one or if it is a "wontfix". One possible hackish solution might be to simply not drop the last dimension here:

https://github.com/stan-dev/posterior/blob/0184c56f0f6f7a7f9183f418983c1d028fef2942/R/summarise_draws.R#L129

i.e. instead converting to a 3-dimensional array: iterations x chains x 1. I think that would force `var()` to behave sensibly, though I don't know if it would break other summary functions.


## logistics

Since there's a bunch of minor things here now, I plan to keep converting TODOs to checkboxes on this issues as they're agreed upon and spinning off larger issues as needed. That said, I'm not sure your preferred merging workflow @paul-buerkner  --- would you like me to fix all these things under this issue on a separate branch and make a single PR when they're done (or a few occasional PRs), or would you prefer many smaller PRs? Also do you prefer review for all changes, or would you rather I merge minor things without bothering you (obviously as long as tests pass) unless I think it is big enough to warrant review? Let me know.

**Comment by paul-buerkner** [comment] 2021-04-03 08:41
Thanks Aki and Matthew for your comments and ideas. 

Regarding logistics, feel free to just merge minor things without review at your own discretion. That way we can speed up the development process at this stage.

I have to think about your other suggestions but at the first glance, they look good and reasonable to me. 

With regard to sd() and var() I would think it would be nice to have them for rvars as users will be constantly confused by those not working. Making sd() generic in the way we need sounds sensible to me.

**Comment by paul-buerkner** [comment] 2021-04-03 10:58
On my machine, one rvar test currently fails with

```R
Failure (test-rvar-print.R:64:3): vec_ptype_abbr and vec_ptype_full work
vec_ptype_abbr(x) not equal to "rvar".
1/1 mismatches
x[1]: "rvar[,4]"
y[1]: "rvar"
```

@mjskay does this happen on your machine as well?

**Comment by rok-cesnovar** [comment] 2021-04-03 11:25
Those fail in all tests: https://github.com/stan-dev/posterior/runs/2259420825

**Comment by mjskay** [comment] 2021-04-03 16:26
Thanks! Looks like it was due to a minor change in vctrs 0.3.7. Fixed it.

**Comment by mjskay** [comment] 2021-04-03 17:30
Note: I updated the table of summary functions in my earlier comment to give a more comprehensive and specific proposal, with a few notes/questions where feedback would be helpful.

**Comment by avehtari** [comment] 2021-04-04 16:02
@mjskay your reply summary and suggestions how to go forward look great. I'll create a separate issue for discussion about MCSE. At the moment I think I would prefer a function for pretty printing without another variable type.

**Comment by paul-buerkner** [comment] 2021-04-04 16:22
I agree with Aki, your ides look great! feel free to prepare PR(s) for
these and let me know if you want me to review some (at your own
discretion; not needed for smaller things).

Aki Vehtari ***@***.***> schrieb am So., 4. Apr. 2021, 18:02:

**Comment by mjskay** [comment] 2021-04-04 16:51
Thanks both! Will do

**Comment by mjskay** [comment] 2021-06-29 21:22
With recent merges (#153, #172) I believe everything in this issue is now addressed. I am closing it (unless someone objects, then we can reopen) and suggest that additional rvar-related things be filed as new issues. Thanks everyone for all the feedback and testing on this!

**Closed by mjskay** 2021-06-29 21:22 UTC
Labels: good first issue
